<img style="float: left; margin: 30px 15px 15px 15px;" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTFzQj91sOlkeDFkg5HDbjtR4QJYmLXkfMNig&usqp=CAU" width="400" height="500" /> 
    
    
### <font color='navy'> Simulación matemática. 

**Nombres:** Mariana Ripoll Batiz 

**Fecha:** 10 de septiembre del 2023.

**Expediente** : 747684.
    
**Profesor:** Oscar David Jaramillo Zuluaga.
    
**Link Github**: https://github.com/marianaripoll/Tarea8_MRipoll.git

# Tarea 3: Problema 8

## 8. Tarea 

### 8.1. Otro problema de transporte

La empresa Carbones de oriente debe ingresar a la empresa un requerimiento mínimo diario de carbón de $5000$ kg de carbón de alto volátil, $4000$ kg de medio volátil y $3000$ kg de bajo volátil para su debido proceso y trasformación. 

La entrada de estos se da en la siguiente tabla (los valores corresponden a un viaje en kg): 

-|Alto volátil|Medio volátil|Bajo volátil
:----|----|----|----
Mina sur|80|70|65
Mina norte|60|50|40
Mina central|40|30|20

El costo del trasporte de un viaje de cada mina es de 2500 dólares, 1500 dólares y 900 dólares, respectivamente. ¿Cuántos viajes de cada mina se deben recibir a diario para suplir los requerimientos mínimos y generar el menor costo de transporte? 

Para simplificar la notación use las siguientes variables: 

+ $x_1:$ Cantidad de viajes de la mina sur  
+ $x_2:$ Cantidad de viajes de la mina norte  
+ $x_3:$ Cantidad de viajes de la mina central  


El objetivo consiste consiste en plantear el problema de programación lineal que permita satisfacer los requerimientos de la empresa Carbones de oriente y resolverlo con `linprog`.

### Ejercicio 1: (enunciado) Transcribirlo

Coste para minimizar:

$2500x_1 + 1500x_2 + 900x_3$

Restricciones: 

a)  $80x_1 + 60x_2 + 40x_3 \geq 5000$

b)  $70x_1 + 50x_2 + 30x_3 \geq 4000$

c)  $65x_1 + 40x_2 + 20x_3 \geq 3000$

El problema es expresado:

$
\begin{align}
min_{x_1,x_2,x_3} &   2500x_1 + 1500x_2 + 900x_3 \\
                  & -80x_1 - 60x_2 - 40x_3 \leq -5000 \\
                  & -70x_1 - 50x_2 - 30x_3 \leq -4000 \\
                  & -65x_1 - 40x_2 - 20x_3 \leq -3000 \\
\end{align}
$

In [8]:
import numpy as np
import scipy.optimize as opt

In [9]:
#Matrices
c = np.array([2500,1500,900])
A_ub = np.array([
    [-80,-60,-40],
    [-70,-50,-30],
    [-65,-40,-20]])
b_ub = np.array([-5000,-4000,-3000])
c, A_ub, b_ub

(array([2500, 1500,  900]),
 array([[-80, -60, -40],
        [-70, -50, -30],
        [-65, -40, -20]]),
 array([-5000, -4000, -3000]))

In [10]:
#Linprog
sol_farma = opt.linprog(c, A_ub, b_ub)
sol_farma

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: 120000.0
              x: [ 0.000e+00  5.000e+01  5.000e+01]
            nit: 2
          lower:  residual: [ 0.000e+00  5.000e+01  5.000e+01]
                 marginals: [ 3.250e+02  0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  0.000e+00  0.000e+00]
                 marginals: [-1.500e+01 -0.000e+00 -1.500e+01]
 mip_node_count: 0
 mip_dual_bound: 0.0
        mip_gap: 0.0

In [7]:
#Vector 
x = sol_farma.x
x

array([ 0., 50., 50.])

En conclusión:  
0 viajes desde la mina sur.
50 viajes desde la mina norte. 
0 viajes  desde la mina central. 
De está manera se cumplen los requisitos mínimos de carbón teniendo el menor costo posible que es igual a 120,000. 




### 8.2. 
Una empresa de muebles rústicos fabrica entre muchos otros productos cinco tipos de sillas A, B, C, D Y E, las cuales se venden a precio de $1100$, $1300$, $1200$, $980$ y $1010$ pesos cada una y respectivamente. 

Las sillas pasan por cinco procesos: corte, ensamblado, lijado, pintado y sellado, para lo cual se dispone máximo de $17$, $11$, $15$, $12$ y $14$ horas respectivamente a la semana para dedicar a estas operaciones a estos productos.

Los requerimientos, en horas, para cada una de las sillas está dado en la siguiente tabla:

-|Corte|Ensamblado|Lijado|Pintado|Sellado
:----|----|----|----|----|----
Silla A|3|1|3|1|1
Silla B|2|3|2|2|3
Silla C|5|2|2|3|1
Silla D|2|4|1|1|2
Silla E|1|0|2|2|3

¿Cuántas sillas de cada tipo se deben fabricar para suplir los requerimientos de disponibiladas semanal y generar la mayor utilidad en ventas? 

Para simplificar la notación use las siguientes variables: 

+ $x_A:$ Cantidad de sillas tipo A 
+ $x_B:$ Cantidad de sillas tipo B 
+ $x_C:$ Cantidad de sillas tipo C 
+ $x_D:$ Cantidad de sillas tipo D  
+ $x_E:$ Cantidad de sillas tipo E


El objetivo consiste consiste en plantear el problemade programación lineal que permita satisfacer los requerimientos de la empresa empresa de muebles y resolverlo con `linprog`.

Coste para maximizar:

$ 1100x_A + 1300x_B + 1200x_C + 980x_D + 1010x_E $$

Restricciones:

$
3x_A + 2x_B + 5x_C + 2x_D + 1x_E \leq 17 \\
1x_A + 3x_B + 2x_C + 4x_D \leq 11 \\
3x_A + 2x_B + 2x_C + 1x_D + 2x_E \leq 15 \\
1x_A + 2x_B + 3x_C + 1x_D + 2x_E \leq 12 \\
1x_A + 3x_B + 1x_C + 2x_D + 3x_E \leq 14 \\
$


El problema es expresado:

$
\begin{align}
min_{x_A,x_B,..} &-1100x_A - 1300x_B - 1200x_C - 980x_D - 1010x_E \\  
\\
                  & 3x_A + 2x_B + 5x_C + 2x_D + 1x_E \leq 17 \\
                  & 1x_A + 3x_B + 2x_C + 4x_D \leq 11 \\
                  & 3x_A + 2x_B + 2x_C + 1x_D + 2x_E \leq 15 \\
                  & 1x_A + 2x_B + 3x_C + 1x_D + 2x_E \leq 12 \\
                  & 1x_A + 3x_B + 1x_C + 2x_D + 3x_E \leq 14 \\
\end{align}
$



In [16]:
import scipy.optimize as opt
import numpy as np

In [13]:
c = np.array([-1100, -1300, -1200, -980, -1010])
A_ub = np.array([
    [3, 2, 5, 2, 1],
    [1, 3, 2, 4, 0],
    [3, 2, 2, 1, 2],
    [1, 2, 3, 1, 2],
    [1, 3, 1, 2, 3]])
b_ub = np.array([17,11,15,12,14])
c, A_ub, b_ub

(array([-1100, -1300, -1200,  -980, -1010]),
 array([[3, 2, 5, 2, 1],
        [1, 3, 2, 4, 0],
        [3, 2, 2, 1, 2],
        [1, 2, 3, 1, 2],
        [1, 3, 1, 2, 3]]),
 array([17, 11, 15, 12, 14]))

In [14]:
sol_farma = opt.linprog(c,A_ub,b_ub)
sol_farma

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -7699.999999999999
              x: [ 2.000e+00  1.000e+00  1.000e+00  1.000e+00  2.000e+00]
            nit: 5
          lower:  residual: [ 2.000e+00  1.000e+00  1.000e+00  1.000e+00
                              2.000e+00]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00]
          upper:  residual: [       inf        inf        inf        inf
                                    inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00]
          eqlin:  residual: []
                 marginals: []
        ineqlin:  residual: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00]
                 marginals: [-7.806e+01 -7.065e+01 -2.023e+02 -3.774e+01
                             -1.506e+02]
 mi

In [15]:
#Vector
x = sol_farma.x
x

array([2., 1., 1., 1., 2.])

En conclusión, para lograr generar ingresos de 7700, se debe de fabricar; 2 sillas A, 1 silla B, 1 silla C, 1 silla D, 2 sillas E.  

### Respuesta planteada en el ejercicio usando (markdown)
 La respuesta es .........